/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package 德州扑克;

import org.junit.Test;
import org.testng.asserts.Assertion;
import java.util.ArrayList;
import java.util.Collections;
import static org.junit.Assert.*


public class AppTest{
    @org.junit.Test
    public void compare(){
        ArrayList<Pai> ceshi1 = new ArrayList<>();
        ArrayList<Pai> ceshi2 = new ArrayList<>();
        Collections.addAll(ceshi1, new Pai(3, 2), new Pai(1, 3), new Pai(2, 5), new Pai(4, 9), new Pai(1, 13));
        Collections.addAll(ceshi2, new Pai(4, 2), new Pai(3, 3), new Pai(2, 4), new Pai(4, 8), new Pai(3, 14));
        Player black = new Player("Black", ceshi1);
        Player white = new Player("White", ceshi2);
        Kanpai.kanpai(black, white);
        String ceshiresult1 = Compare.compare( black,white);
        assertEquals("White wins",ceshiresult1 + ":win");


        black.getList().clear();
        white.getList().clear();
        ceshi1.clear();
        ceshi2.clear();

        Collections.addAll(ceshi1, new Pai(3, 2), new Pai(2, 4), new Pai(4, 4), new Pai(1, 2), new Pai(3, 4));
        Collections.addAll(ceshi2, new Pai(2, 2), new Pai(2, 8), new Pai(2, 14), new Pai(2, 12), new Pai(2, 3));
        black.setList(ceshi1);
        white.setList(ceshi2);
        Kanpai.kanpai(black, white);
        String ceshiresult2 = Compare.compare( black,white);
        assertEquals("White wins",ceshiresult2 + ":win");

        black.getList().clear();
        white.getList().clear();
        ceshi1.clear();
        ceshi2.clear();


        Collections.addAll(ceshi1, new Pai(3, 2), new Pai(1, 3), new Pai(2, 5), new Pai(4, 9), new Pai(1, 13));
        Collections.addAll(ceshi2, new Pai(4, 2), new Pai(3, 3), new Pai(2, 4), new Pai(4, 8), new Pai(3, 13));
        black.setList(ceshi1);
        white.setList(ceshi2);
        Kanpai.kanpai(black, white);
        String ceshiresult3 = Compare.compare(black,white);
        assertEquals("Black wins",ceshiresult3 + ":wins");

    }
}
